version: '2'

services:
  vault:
    build: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
      - VAULT_DEV_LISTEN_ADDRESS=vault:8200
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
  rundeck:
    hostname: rundeck
    build:
      context: rundeck
    links:
    - vault
    environment:
    - RUNDECK_GRAILS_URL=http://localhost:4440
    - RUNDECK_NODE=rundeck1
    - SETUP_TEST_PROJECT=vaulttest
    - RUNDECK_STORAGE_PROVIDER_1_TYPE=keys/db
    - RUNDECK_STORAGE_PROVIDER_1_PATH=db
    - RUNDECK_STORAGE_PROVIDER_2_TYPE=vault-storage
    - RUNDECK_STORAGE_PROVIDER_2_PATH=keys/vault
    - RUNDECK_STORAGE_PROVIDER_2_CONFIG_PREFIX=rundeck
    - RUNDECK_STORAGE_PROVIDER_2_CONFIG_ADDRESS=http://vault:8200
    - RUNDECK_STORAGE_PROVIDER_2_CONFIG_TOKEN=${VAULT_TOKEN}
    - RUNDECK_STORAGE_PROVIDER_2_CONFIG_BEHAVIOUR=vault
    - VAULT_TOKEN=${VAULT_TOKEN}
    ports:
    - "4440:4440"